// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJCnjT6K0xCY73jcKtHFyjOPJfhIvZloY',
    appId: '1:551671188266:web:55bf82d9a55659b339ac53',
    messagingSenderId: '551671188266',
    projectId: 'spaceodyssey-82a4d',
    authDomain: 'spaceodyssey-82a4d.firebaseapp.com',
    storageBucket: 'spaceodyssey-82a4d.appspot.com',
    measurementId: 'G-97HZR7V67S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ijllQzaUYxlM60WMVTnjYCWScnu9fi0',
    appId: '1:551671188266:android:057209d6eb4f894339ac53',
    messagingSenderId: '551671188266',
    projectId: 'spaceodyssey-82a4d',
    storageBucket: 'spaceodyssey-82a4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC01JRmRf46yWScbaVaEW5I-4K7buDppHI',
    appId: '1:551671188266:ios:9bfc68369bfc035539ac53',
    messagingSenderId: '551671188266',
    projectId: 'spaceodyssey-82a4d',
    storageBucket: 'spaceodyssey-82a4d.appspot.com',
    iosClientId: '551671188266-kpfpeeraubvhprf1ln1aa1i9kcspngd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.spaceodyssey',
  );
}
